### ISSUE TITLE
Package subpath './augment/rpc' is not defined by "exports" in @polkadot/api

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia.js-1.0-deprecated#58]
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './augment/rpc' is not defined by "exports" in /home/denny/crab-staking-payouts/node_modules/@polkadot/api/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/denny/crab-staking-payouts/node_modules/@darwinia/types/interfaces/augment-api.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'

**Comment by hackfisher** [comment]
Related https://github.com/darwinia-network/darwinia.js/pull/57/files#diff-3d0f496aa3be89d61d8e83be4cb77cf140a52adcd3b16c420f08e133ca8bffc1L4

**Comment by hackfisher** [comment]
Reference: https://github.com/darwinia-network/staking-payouts/pull/3
